set shell := ["bash", "-euo", "pipefail", "-c"]

PANDOC := env_var_or_default("PANDOC", "pandoc")
DIFF := env_var_or_default("DIFF", "diff --strip-trailing-cr -u")

default: test

test:
    @{{PANDOC}} --lua-filter=multiple-bibliographies.lua --standalone --to=native sample.md | {{DIFF}} - expected.native
