set shell := ["bash", "-euo", "pipefail", "-c"]

PANDOC := env_var_or_default("PANDOC", "pandoc")
DIFF := env_var_or_default("DIFF", "diff --strip-trailing-cr -u")

default: test

test:
    @{{PANDOC}} --lua-filter=cito.lua --output=output.md --standalone sample.md
    @{{DIFF}} expected.md output.md
    @rm -f output.md
