set shell := ["bash", "-euo", "pipefail", "-c"]

PANDOC := env_var_or_default("PANDOC", "pandoc")
DIFF := env_var_or_default("DIFF", "diff --strip-trailing-cr -u")

default: test

test:
    @{{PANDOC}} --lua-filter list-table.lua --to=html sample.md | {{DIFF}} expected.html -

update:
    {{PANDOC}} --lua-filter list-table.lua --to=html sample.md > expected.html
