set shell := ["bash", "-euo", "pipefail", "-c"]

PANDOC := env_var_or_default("PANDOC", "pandoc")
DIFF := env_var_or_default("DIFF", "diff --strip-trailing-cr -u")

default: test

# Ensure LaTeX output can be compiled to PDF.
test: sample-pdf
    @{{PANDOC}} -t markdown --wrap=preserve --lua-filter=track-changes.lua sample.md | {{DIFF}} - expected_accept.markdown
    @{{PANDOC}} -t markdown --wrap=preserve --track-changes=reject -M trackChanges:reject --lua-filter=track-changes.lua sample.md | {{DIFF}} - expected_reject.markdown
    @{{PANDOC}} -t html --wrap=preserve --track-changes=all -M trackChanges:all --lua-filter=track-changes.lua sample.md | {{DIFF}} - expected_draft.html
    @{{PANDOC}} -M trackChanges:all --track-changes=all --wrap=preserve --to=latex --lua-filter=track-changes.lua --standalone sample.md | sh test-track-changes.sh
    @rm -f sample.pdf

sample-pdf:
    @{{PANDOC}} -M trackChanges:all --track-changes=all --lua-filter=track-changes.lua --output sample.pdf sample.md

clean:
    rm -f sample.pdf
